---
title: "饶欣然关系网"
author: "饶一率整理"
date: "2023/8/23"
output: 
  html_document:
    toc: true
    css: mystyles.css

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## 人际关系网
该人际关系网基于组织，活动，爱好三个方面。

### 1 轮廓图






### 2 人际关系图


```{r,echo = FALSE}
#我们要处理的第一个数据集由两个文件组成，`People-Yun-EDGES.csv`和`People-Yun-NODES.csv`
library('network')
nodes <- read.csv("People-Yun-NODES.csv", header=T, as.is=T)
links <- read.csv("People-Yun-EDGES.csv", header=T, as.is=T)
head(nodes)
head(links)
library(networkD3)
# 重新编码边
links.d3 <- data.frame(from=as.numeric(factor(links$from))-1, 
                       to=as.numeric(factor(links$to))-1 )
# 重新编码点
nodes.d3 <- cbind(idn=factor(nodes$glossary), nodes) 
# 绘图
forceNetwork(Links = links.d3, Nodes = nodes.d3, Source="from", Target="to",
               NodeID = "idn", Group = "glossary.type",linkWidth = 1,
               linkColour = "#afafaf", fontSize=12, zoom=T, legend=T,
               Nodesize=6, opacity = 0.8, charge=-300, 
               width = 600, height = 400)


library('visNetwork') 
#visNetwork(nodes, links, width="100%", height="400px", background="#eeefff",           main="Network", submain="And what a great network it is!",           footer= "Hyperlinks and mentions among media sources")
vis.nodes <- nodes
vis.links <- links
## 节点属性
vis.nodes$shape  <- "dot"  
vis.nodes$shadow <- TRUE # 节点会投下阴影
vis.nodes$title  <- vis.nodes$gender   # 点击出现的文本
vis.nodes$label  <- vis.nodes$glossary  # 直接出现的文本
#vis.nodes$size   <- vis.nodes$audience.size # 节点的大小
vis.nodes$size <- 30
vis.nodes$font.size <- 36
vis.nodes$borderWidth <- 2 # 节点边缘的线条宽度
vis.nodes$color.background <- c("slategrey", "tomato","gold","orange")[vis.nodes$gender.type]
vis.nodes$color.border <- "black"
vis.nodes$color.highlight.background <- "orange"
vis.nodes$color.highlight.border <- "darkred"
## 边属性
vis.links$width <- 3
vis.links$label <- vis.links$type

## 绘图
visnet <- visNetwork(vis.nodes, vis.links, main="基于组织，活动，爱好的人际关系图", submain="饶欣然")
visnet
#visOptions(visnet, highlightNearest = TRUE, selectedBy = "glossary.type")

```



