---
title: "PeopleNet1.0"
author: "饶一率"
date: "2023/8/8"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
```

## 这是一个制作人物关系网的R语言教程

### 1 必要的安装
* R-base
* RStudio
* rmarkdown
* networkD3

### 2 使用
在Rstudio中打开本rmd文件，点击 **Knit** 按钮可以生成一个html文件。

### 3 数据准备-excel
按照这个格式组织xlsx文件
```{r}
library(openxlsx)
Filepath <- "./PeopleNet1.xlsx"
nodesData <- read.xlsx(Filepath,"nodes")
edgesData <- read.xlsx(Filepath,"edges")
str(nodesData)
head(edgesData)
```
### 4 画图
```{r}
# 加载包
library(networkD3)
# 画网络图
forceNetwork(Links = edgesData,#线性质数据框
             Nodes = nodesData,#节点性质数据框
             Group = "group", #节点分组 节点数据中对应的列名
             Source = "source",#连线的源变量 边数据中起始点ID
             Target = "target",#连线的目标变量 边数据中终点ID
             Value = "Value", #边的粗细值，边数据中共现频率列名
             NodeID = "namelist", #节点名称
             Nodesize = "Freq" , #节点大小，节点数据框中节点频率列名
             ###美化部分
             fontSize = 30, #节点文本标签的数字字体大小（以像素为单位）。
             linkColour="grey",#连线颜色,black,red,blue,  
             colourScale = JS("d3.scaleOrdinal(d3.schemeCategory10);"),
              #colourScale ,linkWidth,#节点颜色,red，蓝色blue,cyan,yellow等
             charge = -2000,#数值表示节点排斥强度（负值）或吸引力（正值）  
             opacity = 0.5, #节点透明度
             #nodeColour="black",
             fontFamily = "黑体",
             arrows=F, #是否带方向
             bounded=F, #是否启用限制图像的边框
             opacityNoHover=2, #当鼠标悬停在其上时，节点标签文本的不透明度比例的数值
             zoom = T, #允许放缩，双击放大
             #clickAction = MyClickScript
             )
```
